### ISSUE TITLE
npm install problem

### ISSUE THREAD

**Issue by winkler1** [bigardone/phoenix-react-redux-template#2]
thanks for this project and the blog series, awesome work.

getting a problem installing--

```
npm ERR! addLocal Could not install /Users/Jeff/repos/ghtemp/deps/phoenix
npm ERR! addLocal Could not install /Users/Jeff/repos/ghtemp/deps/phoenix_html
```

due to this in package.json?

```
    "phoenix": "file:deps/phoenix",
    "phoenix_html": "file:deps/phoenix_html",
```

**Comment by bigardone** [comment]
@winkler1 have you run `mix deps.get` before the npm installation? In Phoenix's latest version it gets 
both packages from the dependencies folder,

**Comment by winkler1** [comment]
ah, thanks!

**Comment by bigardone** [comment]
No problem! :)
