### ISSUE TITLE
module is not defined

### ISSUE THREAD

**Issue by winkler1** [bigardone/phoenix-react-redux-template#3]
Looks like I'm running into every noob issue in the book :)  

```
$ node -v
v4.2.6
$ npm -v
2.14.12
```

I got `error: Compiling of web/static/js/app.js failed. Couldn't find preset "es2015" relative to directory "web/static/js"`, googled and found http://stackoverflow.com/questions/34345573/couldnt-find-preset-es2015-relative-to-directory-web-static-js. Fixed by `npm install --save-dev babel-preset-es2015` (have found npm3 slow/cpu hog on another machine, so not in a hurry to upgrade)

Now getting-
![image](https://cloud.githubusercontent.com/assets/883896/12695775/688da3a0-c726-11e5-977a-9e46689c9ebc.png)

**Comment by bigardone** [comment]
Hey @winkler1 thank you very much, good catch! I've solved it in this new commit:

https://github.com/bigardone/phoenix-react-redux-template/commit/8d684be9cb9f537795bb86d5a58fe4191d6e3f97

Cheers!
